### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by nemobis** [yarl/jurytool#1]
Hi, thanks for the tool.
I'm about to clone the repository, could you please add a license statement so that I don't violate copyright? :)

**Comment by yarl** [comment]
@nemobis: Hi, license added. However code is probably messy and you need to add data to database by yourself. If you need some help, mail me.

**Comment by nemobis** [comment]
Paweł Marynowski, 08/10/2015 22:21:

> @nemobis https://github.com/nemobis: Hi, license added. However code
> is probably messy and you need to add data to database by yourself. If
> you need some help, mail me.

Actually it was not _that_ bad, I'll submit my local adaptations later.
